"""add article photo tables

Revision ID: 0bca2f665c3b
Revises: 
Create Date: 2026-05-08 01:43:50.036878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bca2f665c3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('classes')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='classes_pkey')
    )
    op.drop_table('article_photos')
    op.drop_table('article_photo')
    op.drop_table('class')
    # ### end Alembic commands ###
