"""empty message

Revision ID: 5c2f9e54fb59
Revises: 9123841ba456
Create Date: 2024-12-12 17:10:38.036529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2f9e54fb59'
down_revision = '9123841ba456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_url', sa.String(length=2083), nullable=True))
        batch_op.add_column(sa.Column('is_streamable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchases', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('purchases')
        batch_op.drop_column('views')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('price')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')
        batch_op.drop_column('is_streamable')
        batch_op.drop_column('streaming_url')

    # ### end Alembic commands ###
