"""empty message

Revision ID: 9123841ba456
Revises: 415c5fba7b47
Create Date: 2024-12-09 13:38:59.503862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9123841ba456'
down_revision = '415c5fba7b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_part1', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('content_part2', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content_part2')
        batch_op.drop_column('content_part1')

    # ### end Alembic commands ###
