"""empty message

Revision ID: a0300a22ee36
Revises: 5c2f9e54fb59
Create Date: 2025-01-16 23:46:20.933620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0300a22ee36'
down_revision = '5c2f9e54fb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content_part2',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content_part2',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
